package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EnsembleSpec defines a bundle of pre-configured agent personas.
// Installing an Ensemble stamps out SympoziumInstances, SympoziumSchedules,
// and optionally seeds memory for each persona.
type EnsembleSpec struct {
	// Enabled controls whether the controller stamps out resources for this ensemble.
	// Ensembles default to disabled (catalog-only) and must be explicitly
	// activated — for example via the TUI or kubectl patch.
	// +optional
	Enabled bool `json:"enabled,omitempty"`

	// Description is a human-readable summary of this ensemble.
	// +optional
	Description string `json:"description,omitempty"`

	// Category classifies this ensemble (e.g. "platform", "security", "devops").
	// +optional
	Category string `json:"category,omitempty"`

	// Version is the ensemble version.
	// +optional
	Version string `json:"version,omitempty"`

	// Personas is the list of agent personas in this ensemble.
	Personas []PersonaSpec `json:"personas"`

	// AuthRefs references secrets containing AI provider credentials.
	// Applied to all generated SympoziumInstances. Set during install.
	// +optional
	AuthRefs []SecretRef `json:"authRefs,omitempty"`

	// ExcludePersonas lists persona names to skip during reconciliation.
	// Personas listed here will not have their Instance/Schedule created,
	// and existing resources for them will be deleted. Set by the TUI when
	// a user disables an individual persona.
	// +optional
	ExcludePersonas []string `json:"excludePersonas,omitempty"`

	// ChannelConfigs maps channel types to their credential secret names.
	// Populated during persona onboarding when users provide channel tokens.
	// The controller uses this to set ConfigRef on generated instances.
	// +optional
	ChannelConfigs map[string]string `json:"channelConfigs,omitempty"`

	// PolicyRef references the SympoziumPolicy to apply to all generated instances.
	// +optional
	PolicyRef string `json:"policyRef,omitempty"`

	// BaseURL overrides the provider's default API endpoint for all generated instances.
	// Set during onboarding for local providers (e.g. Ollama, LM Studio) that do not
	// require authentication.
	// +optional
	BaseURL string `json:"baseURL,omitempty"`

	// ModelRef references a Model CR for cluster-local inference.
	// When set, the controller resolves the Model's endpoint and configures all
	// generated instances to use it (provider=openai, baseURL=endpoint, no auth).
	// Takes precedence over AuthRefs and BaseURL.
	// +optional
	ModelRef string `json:"modelRef,omitempty"`

	// SkillParams provides per-skill parameters applied to all generated instances.
	// The outer key is the SkillPack name (e.g. "github-gitops"), and the inner map
	// holds key/value pairs injected as SKILL_<KEY> environment variables.
	// Set during onboarding when the user configures skill-specific settings.
	// +optional
	SkillParams map[string]map[string]string `json:"skillParams,omitempty"`

	// TaskOverride replaces each persona's default schedule task with a
	// team-level objective. Set during onboarding when the user provides
	// instructions for the team. Each persona's schedule task is prepended
	// with this directive so every agent works toward the same goal.
	// +optional
	TaskOverride string `json:"taskOverride,omitempty"`

	// ChannelAccessControl maps channel types to their access control rules.
	// Propagated to generated instances during reconciliation.
	// +optional
	ChannelAccessControl map[string]*ChannelAccessControl `json:"channelAccessControl,omitempty"`

	// AgentSandbox configures the Kubernetes Agent Sandbox (CRD) execution backend
	// for all instances generated by this ensemble. When enabled, agent runs use Sandbox
	// CRs with gVisor/Kata kernel-level isolation.
	// +optional
	AgentSandbox *AgentSandboxInstanceSpec `json:"agentSandbox,omitempty"`

	// SharedMemory configures a shared memory pool accessible to all personas
	// in this ensemble. Each persona retains its private memory; the shared pool
	// provides cross-persona knowledge sharing within the workflow.
	// +optional
	SharedMemory *SharedMemorySpec `json:"sharedMemory,omitempty"`

	// Relationships defines directed edges between personas in the ensemble,
	// enabling coordination patterns like delegation, sequential pipelines,
	// and supervision.
	// +optional
	Relationships []PersonaRelationship `json:"relationships,omitempty"`

	// WorkflowType describes the overall orchestration pattern for this ensemble.
	// "autonomous" (default): personas run independently on their own schedules.
	// "pipeline": personas execute in sequence defined by sequential edges.
	// "delegation": personas can actively delegate to each other at runtime.
	// +kubebuilder:validation:Enum=autonomous;pipeline;delegation
	// +kubebuilder:default="autonomous"
	// +optional
	WorkflowType string `json:"workflowType,omitempty"`
}

// PersonaSpec defines a single agent persona within an Ensemble.
type PersonaSpec struct {
	// Name is the persona identifier (used as suffix in generated instance names).
	Name string `json:"name"`

	// DisplayName is the human-readable name shown in the TUI.
	// +optional
	DisplayName string `json:"displayName,omitempty"`

	// SystemPrompt is the system prompt that defines the agent's role and behaviour.
	SystemPrompt string `json:"systemPrompt"`

	// Model overrides the default model for this persona.
	// If empty, the ensemble-level or onboarding-time model is used.
	// +optional
	Model string `json:"model,omitempty"`

	// Skills lists SkillPack references to mount into the agent pod.
	// +optional
	Skills []string `json:"skills,omitempty"`

	// ToolPolicy defines which tools this persona is allowed to use.
	// +optional
	ToolPolicy *PersonaToolPolicy `json:"toolPolicy,omitempty"`

	// Schedule defines a recurring task for this persona.
	// +optional
	Schedule *PersonaSchedule `json:"schedule,omitempty"`

	// Memory defines initial memory seeds for this persona.
	// +optional
	Memory *PersonaMemory `json:"memory,omitempty"`

	// Channels lists channel types this persona should be bound to after install.
	// Users can modify channel bindings later via the TUI edit modal.
	// +optional
	Channels []string `json:"channels,omitempty"`

	// WebEndpoint configures the web endpoint for this persona.
	// +optional
	WebEndpoint *PersonaWebEndpoint `json:"webEndpoint,omitempty"`

	// Lifecycle defines pre and post run hooks for this persona.
	// Propagated to the generated SympoziumInstance's AgentConfig.
	// +optional
	Lifecycle *LifecycleHooks `json:"lifecycle,omitempty"`

	// ChannelAccessControl maps channel types to per-persona access control
	// overrides. When set, these take priority over ensemble-level
	// ChannelAccessControl for this persona. Use AllowedChats with Discord
	// channel IDs to route specific Discord channels to this persona.
	// +optional
	ChannelAccessControl map[string]*ChannelAccessControl `json:"channelAccessControl,omitempty"`
}

// PersonaWebEndpoint configures the web endpoint for a persona.
type PersonaWebEndpoint struct {
	// Enabled indicates whether the web endpoint is active.
	Enabled bool `json:"enabled"`

	// Hostname overrides the auto-derived hostname.
	// +optional
	Hostname string `json:"hostname,omitempty"`
}

// PersonaToolPolicy defines tool access for a persona.
type PersonaToolPolicy struct {
	// Allow lists explicitly allowed tools.
	// +optional
	Allow []string `json:"allow,omitempty"`

	// Deny lists explicitly denied tools.
	// +optional
	Deny []string `json:"deny,omitempty"`
}

// PersonaSchedule defines a recurring task configuration for a persona.
type PersonaSchedule struct {
	// Type categorises the schedule: heartbeat, scheduled, or sweep.
	// +kubebuilder:validation:Enum=heartbeat;scheduled;sweep
	// +kubebuilder:default="heartbeat"
	Type string `json:"type"`

	// Interval is a human-readable interval (e.g. "30m", "1h", "6h").
	// Converted to a cron expression by the controller.
	// +optional
	Interval string `json:"interval,omitempty"`

	// Cron is a raw cron expression. Takes precedence over Interval.
	// +optional
	Cron string `json:"cron,omitempty"`

	// Task is the task description sent to the agent on each trigger.
	Task string `json:"task"`
}

// PersonaMemory defines initial memory configuration for a persona.
type PersonaMemory struct {
	// Enabled indicates whether persistent memory is active.
	// +kubebuilder:default=true
	Enabled bool `json:"enabled"`

	// Seeds is a list of initial memory entries injected into MEMORY.md.
	// +optional
	Seeds []string `json:"seeds,omitempty"`
}

// SharedMemorySpec configures a shared memory pool for all personas in an ensemble.
type SharedMemorySpec struct {
	// Enabled activates the shared memory server for this ensemble.
	// +kubebuilder:default=false
	Enabled bool `json:"enabled"`

	// StorageSize is the PVC storage request for the shared memory database.
	// Defaults to "1Gi".
	// +kubebuilder:default="1Gi"
	// +optional
	StorageSize string `json:"storageSize,omitempty"`

	// AccessRules defines per-persona access controls for the shared memory.
	// If empty, all personas get read-write access.
	// +optional
	AccessRules []SharedMemoryAccessRule `json:"accessRules,omitempty"`
}

// SharedMemoryAccessRule defines access control for a specific persona.
type SharedMemoryAccessRule struct {
	// Persona is the persona name this rule applies to.
	Persona string `json:"persona"`

	// Access is the access level: "read-write" or "read-only".
	// +kubebuilder:validation:Enum="read-write";"read-only"
	// +kubebuilder:default="read-write"
	Access string `json:"access"`
}

// PersonaRelationship defines a directed edge between two personas in an ensemble.
type PersonaRelationship struct {
	// Source is the persona name that initiates the interaction.
	Source string `json:"source"`

	// Target is the persona name that receives the interaction.
	Target string `json:"target"`

	// Type categorises the relationship.
	// "delegation": source requests target and awaits the result.
	// "sequential": source must complete before target starts.
	// "supervision": source monitors target (observability only, no runtime effect).
	// +kubebuilder:validation:Enum=delegation;sequential;supervision
	Type string `json:"type"`

	// Condition is an optional description of when this edge activates
	// (e.g. "when source run succeeds", "on explicit request").
	// +optional
	Condition string `json:"condition,omitempty"`

	// Timeout is the maximum duration to wait for the target to complete.
	// Applies to delegation and sequential types. Format: "5m", "1h".
	// +optional
	Timeout string `json:"timeout,omitempty"`

	// ResultFormat constrains the expected output (e.g. "json", "markdown").
	// +optional
	ResultFormat string `json:"resultFormat,omitempty"`
}

// InstalledPersona tracks the resources created for one persona.
type InstalledPersona struct {
	// Name is the persona identifier.
	Name string `json:"name"`

	// InstanceName is the name of the generated SympoziumInstance.
	InstanceName string `json:"instanceName"`

	// ScheduleName is the name of the generated SympoziumSchedule (if any).
	// +optional
	ScheduleName string `json:"scheduleName,omitempty"`
}

// EnsembleStatus defines the observed state of Ensemble.
type EnsembleStatus struct {
	// Phase is the current phase (Pending, Ready, Error).
	// +optional
	Phase string `json:"phase,omitempty"`

	// PersonaCount is the number of personas defined in this ensemble.
	// +optional
	PersonaCount int `json:"personaCount,omitempty"`

	// InstalledCount is the number of personas successfully installed.
	// +optional
	InstalledCount int `json:"installedCount,omitempty"`

	// InstalledPersonas lists the resources created for each persona.
	// +optional
	InstalledPersonas []InstalledPersona `json:"installedPersonas,omitempty"`

	// SharedMemoryReady indicates the shared memory infrastructure is provisioned.
	// +optional
	SharedMemoryReady bool `json:"sharedMemoryReady,omitempty"`

	// Conditions represent the latest available observations.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Enabled",type="boolean",JSONPath=".spec.enabled"
// +kubebuilder:printcolumn:name="Personas",type="integer",JSONPath=".status.personaCount"
// +kubebuilder:printcolumn:name="Installed",type="integer",JSONPath=".status.installedCount"
// +kubebuilder:printcolumn:name="Workflow",type="string",JSONPath=".spec.workflowType"
// +kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// Ensemble is the Schema for the ensembles API.
// It bundles pre-configured agent personas that can be installed to stamp out
// SympoziumInstances, Schedules, and memory seeds.
type Ensemble struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   EnsembleSpec   `json:"spec,omitempty"`
	Status EnsembleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EnsembleList contains a list of Ensemble.
type EnsembleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Ensemble `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Ensemble{}, &EnsembleList{})
}
